#!/bin/sh
echo "-----------------------------------------------------------------------"
KEXT="/System/Library/Extensions/SmoothMouse.kext"
sudo kextload "$KEXT"
echo "-----------------------------------------------------------------------"