#!/bin/sh
KEXT_LOCATION="/System/Library/Extensions/SmoothMouse.kext"
OSX_MINOR_VERSION=`sw_vers -productVersion | cut -d . -f 2`

if [[ $OSX_MINOR_VERSION < 9 ]]; then
	sudo kextload "$KEXT_LOCATION"
fi