#!/bin/sh
echo "-----------------------------------------------------------------------"
KEXT="/System/Library/Extensions/SmoothMouse.kext"
if [ -d "$KEXT" ]; then
    sudo kextunload -quiet "$KEXT"
fi
echo "-----------------------------------------------------------------------"