#!/bin/sh
sudo -u $USER launchctl start "com.cyberic.smoothmouse"
sudo -u $USER osascript "postinstall.scpt"
sudo ln -sf "/Library/PreferencePanes/SmoothMouse.prefPane/Contents/MacOS/smoothmoused" "/usr/bin/smoothmouse"
exit 0